version: 2
jobs:
  build:
    docker:
      - image: node:lts-alpine  # (1)
    #working_directory: /go/src/bitbucket.org/darkness-corp
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="19.03.4"
            apk --no-cache add curl
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      # build and push Docker image
      - run: |
          # Build Image
          TAG=latest
          docker build -t tupk/crm-pccc-application:$TAG .

          # Push Image to Docker Hub
          docker login -u tupk -p phungkhactu         # (4)
          docker push tupk/crm-pccc-application:$TAG
